parameters:
- name: variable_group_name
  displayName: Variable Group
  type: string
  default: 'Image Generation Variables'
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: 'Host Pool - Image'
- name: repository_base_path
  displayName: Scripts Path
  type: string
  default: .

jobs:
- job: CleanOrphanedManagedImages
  displayName: Cleanup orphaned Managed Images
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  variables:
  - group: ${{ parameters.variable_group_name }}

  steps:
  - checkout: self
  - ${{ if ne(parameters.repository_base_path, '.') }}:
    - checkout: ${{ parameters.repository_base_path }}
  - task: PowerShell@2
    displayName: 'Backwards compatible variables'
    inputs:
      targetType: 'inline'
      script: |
        $LCL_AZURE_AGENTS_RESOURCE_GROUP = If (![string]::IsNullOrWhiteSpace($AZUREAGENTSRESOURCEGROUP)) { $AZUREAGENTSRESOURCEGROUP } ElseIf (![string]::IsNullOrWhiteSpace($AZURE_AGENTS_RESOURCE_GROUP)) { $AZURE_AGENTS_RESOURCE_GROUP } Else { $null }
        $LCL_AZURE_LOCATION = If (![string]::IsNullOrWhiteSpace($AZURELOCATION)) { $AZURELOCATION } ElseIf (![string]::IsNullOrWhiteSpace($AZURE_LOCATION)) { $AZURE_LOCATION } Else { $null }
        $LCL_AZURE_SUBSCRIPTION = If (![string]::IsNullOrWhiteSpace($AZURESUBSCRIPTION)) { $AZURESUBSCRIPTION } ElseIf (![string]::IsNullOrWhiteSpace($AZURE_SUBSCRIPTION)) { $AZURE_SUBSCRIPTION } Else { $null }
        $LCL_BUILD_AGENT_VNET_NAME = If (![string]::IsNullOrWhiteSpace($BUILDAGENTVNETNAME)) { $BUILDAGENTVNETNAME } ElseIf (![string]::IsNullOrWhiteSpace($BUILD_AGENT_VNET_NAME)) { $BUILD_AGENT_VNET_NAME } Else { $null }
        $LCL_BUILD_AGENT_VNET_RESOURCE_GROUP = If (![string]::IsNullOrWhiteSpace($BUILDAGENTVNETRESOURCEGROUP)) { $BUILDAGENTVNETRESOURCEGROUP } ElseIf (![string]::IsNullOrWhiteSpace($BUILD_AGENT_VNET_RESOURCE_GROUP)) { $BUILD_AGENT_VNET_RESOURCE_GROUP } Else { $null }
        $LCL_BUILD_AGENT_SUBNET_NAME = If (![string]::IsNullOrWhiteSpace($BUILDAGENTSUBNETNAME)) { $BUILDAGENTSUBNETNAME } ElseIf (![string]::IsNullOrWhiteSpace($BUILD_AGENT_SUBNET_NAME)) { $BUILD_AGENT_SUBNET_NAME } Else { $null }
        $LCL_AZURE_TENANT = If (![string]::IsNullOrWhiteSpace($AZURETENANT)) { $AZURETENANT } ElseIf (![string]::IsNullOrWhiteSpace($AZURE_TENANT)) { $AZURE_TENANT } Else { $null }
        $LCL_CLIENT_ID = If (![string]::IsNullOrWhiteSpace($CLIENTID)) { Write-Host "CLIENTID";return $CLIENTID; } ElseIf (![string]::IsNullOrWhiteSpace($CLIENT_ID)) { Write-Host "CLIENT_ID";return $CLIENT_ID; } Else { Write-Host "null";return $null; }
        $LCL_CLIENT_SECRET = If (![string]::IsNullOrWhiteSpace($CLIENTSECRET)) { $CLIENTSECRET } ElseIf (![string]::IsNullOrWhiteSpace($CLIENT_SECRET)) { $CLIENT_SECRET } Else { $null }
        $LCL_RUN_VALIDATION_FLAG = If (![string]::IsNullOrWhiteSpace($RUNVALIDATIONFLAG)) { $RUN_VALIDATION_FLAG } ElseIf (![string]::IsNullOrWhiteSpace($RUN_VALIDATION_FLAG)) { $RUN_VALIDATION_FLAG } Else { $null }
        $LCL_GALLERY_NAME = If (![string]::IsNullOrWhiteSpace($GALLERYNAME)) { $GALLERYNAME } ElseIf (![string]::IsNullOrWhiteSpace($GALLERY_NAME)) { $GALLERY_NAME } Else { $null }
        $LCL_GALLERY_RESOURCE_GROUP = If (![string]::IsNullOrWhiteSpace($GALLERYRESOURCEGROUP)) { $GALLERYRESOURCEGROUP } ElseIf (![string]::IsNullOrWhiteSpace($GALLERY_RESOURCE_GROUP)) { $GALLERY_RESOURCE_GROUP } Else { $null }
        $LCL_VMSS_Windows2019 = If (![string]::IsNullOrWhiteSpace($VMSSWindows2019)) { $VMSSWindows2019 } ElseIf (![string]::IsNullOrWhiteSpace($VMSS_Windows2019)) { $VMSS_Windows2019 } Else { $null }
        $LCL_VMSS_Windows2022 = If (![string]::IsNullOrWhiteSpace($VMSSWindows2022)) { $VMSSWindows2022 } ElseIf (![string]::IsNullOrWhiteSpace($VMSS_Windows2022)) { $VMSS_Windows2022 } Else { $null }
        $LCL_VMSS_Ubuntu2004 = If (![string]::IsNullOrWhiteSpace($VMSSUbuntu2004)) { $VMSSUbuntu2004 } ElseIf (![string]::IsNullOrWhiteSpace($VMSS_Ubuntu2004)) { $VMSS_Ubuntu2004 } Else { $null }
        $LCL_VMSS_Ubuntu2204 = If (![string]::IsNullOrWhiteSpace($VMSSUbuntu2204)) { $VMSSUbuntu2204 } ElseIf (![string]::IsNullOrWhiteSpace($VMSS_Ubuntu2204)) { $VMSS_Ubuntu2204 } Else { $null }
  - task: PowerShell@2
    displayName: 'Cleanup orphaned Managed Images'
    inputs:
      targetType: filePath
      filePath: ${{ parameters.repository_base_path }}/scripts/cleanup-managedimages.ps1
      arguments: -ClientId $(LCL_CLIENT_ID) `
                        -ClientSecret $(LCL_CLIENT_SECRET) `
                        -ResourceGroup $(LCL_AZURE_RESOURCE_GROUP) `
                        -SubscriptionId $(LCL_AZURE_SUBSCRIPTION) `
                        -AgentsResourceGroup $(LCL_AZURE_AGENTS_RESOURCE_GROUP) `
                        -VmssNameWindows $(LCL_VMSS_Windows2019) `
                        -VmssNameWindows2022 $(LCL_VMSS_Windows2022) `
                        -VmssNameUbuntu $(LCL_VMSS_Ubuntu2004) `
                        -VmssNameUbuntu2204 $(LCL_VMSS_Ubuntu2204) `
                        -TenantId $(LCL_AZURE_TENANT)
